### ISSUE TITLE
Vinculação de usuário com perfil

### ISSUE THREAD

**Issue by AndersonMonzani** [fundamento/qpress-api#14]
Um usuário só pode  estar vinculado a um perfil de acesso e um perfil pode estar vinculado há mais de um usuário.

**Comment by luizambrozio** [comment]
@AndersonMonzani esta vinculacao foi prevista com uma many_to_many assim gerando uma tabela aux user_perfils, porem se a necessidade for de que um user tenha somente um perfil basta fazer um many_to_one que elimina esta tabela.

**Comment by AndersonMonzani** [comment]
> @AndersonMonzani esta vinculacao foi prevista com uma many_to_many assim gerando uma tabela aux user_perfils, porem se a necessidade for de que um user tenha somente um perfil basta fazer um many_to_one que elimina esta tabela.

Exatamente. Um usuário terá apenas um perfil e não teremos usuário sem perfil.
